### PR TITLE
build: upgrade yuujinchou

### PR DESCRIPTION
**Pull request by favonia**

### CODE REVIEW

**Comment by solomon-b** [comment]
Thanks for the PR! 

To make this work, at least with Nix, we also need to upgrade `bwd` and pin both `bwd and `yuujinchou`:
```
-  "bwd" {>= "1.1"}
+  "bwd" {>= "2.1"}
```
```
+  [ "yuujinchou.5.0.2" "git+https://github.com/RedPRL/yuujinchou#fdfbb1cfb31fb02420e968bcd75567ed9472e664" ]
+  [ "bwd.2.2.0" "git+https://github.com/RedPRL/ocaml-bwd#f7daa913d29f639886f33193c80e5120bf844d6d" ]
```

Sorry I don't know how to make these inlined suggestions in the PR.

**Comment by favonia** [comment]
@solomon-b There's something I don't understand: why do you have to pin those libraries? bwd 2.2 and yuujinchou 5.0.2 are already available on OPAM. If we have to pin for example yuujinchou, why is it okay not to pin other dependencies?

**Comment by solomon-b** [comment]
> @solomon-b There's something I don't understand: why do you have to pin those libraries? bwd 2.2 and yuujinchou 5.0.2 are already available on OPAM. If we have to pin for example yuujinchou, why is it okay not to pin other dependencies?

TBH I'm not sure. I just know that Opam-Nix was unhappy without the pins. I wonder if it is using an old cached Opam registry without the required versions?

**Comment by favonia** [comment]
@solomon-b That would explain why cooltt also doesn't build. However, if that's the case, I don't feel adding the pin is the solution. :thinking:

**Comment by solomon-b** [comment]
> @solomon-b That would explain why cooltt also doesn't build. However, if that's the case, I don't feel adding the pin is the solution. 🤔

Yeah I would agree with you here. I need to do a little research on how Opam-Nix fetches dependencies. I'll report back here and hopefully we can resolve this for both polytt and cooltt.

**Comment by solomon-b** [comment]
@favonia the problem is that Opam-Nix itself is pinned to an old version of Opam-Repository. We can force it to follow a newer version by changing our flakes like this:
```
+    opam-repository = {
+      url = "github:ocaml/opam-repository";
+      flake = false;
+    };
     opam-nix.url = "github:tweag/opam-nix";
+    opam-nix.inputs.opam-repository.follows = "opam-repository";
     flake-utils.url = "github:numtide/flake-utils";
     nixpkgs.follows = "opam-nix/nixpkgs";
   };
-  outputs = { self, flake-utils, opam-nix, nixpkgs }@inputs:
+  outputs = { self, flake-utils, opam-nix, opam-repository, nixpkgs }@inputs:
```

Now we don't need to pin anything in the opam file. I'll make this same change to my cooltt PR.

**Comment by favonia** [comment]
@solomon-b Thank you. I have two beginner questions:
1. What does `flake = false;` do there?
2. Was the locking done here? https://github.com/tweag/opam-nix/blob/e83bd1d949c5e330a49f89d394b51b744248e3ca/flake.lock#L82-L97

I think it makes sense for cooltt to stay with the latest version of opam-repository. Maybe polytt as well.

**Comment by favonia** [comment]
@solomon-b I believe it builds now, but the cooltt seems to have this fix applied already? I'm confused by why it doesn't seem to work for cooltt. Looking forward to your cooltt PR!

**Review by solomon-b — APPROVED** [review]

**Pull request merged**
